### ISSUE TITLE
Trouble with the removing of features

### ISSUE THREAD

**Issue by RobinGRAPIN** [Simon-Hohberg/Viola-Jones#10]
Hello sir,
I was trying to implement by my own a kind of Viola and Jones programm, and Iloved and adapted your function called "learn", but I'm facing a problem with the removing of features after having selecting one. For the next feature , the line  86 : " best_feature_idx = feature_indexes[min_error_idx] " will sometimes not run because the " min_error_idx " will be bigger than the length of the list... How can I fix it? And even if my indexes stay lower then the list length, is it not going to change the order of features and select a wrong one? Thanks for reading :)

**Comment by Simon-Hohberg** [comment]
Hey,

it is a bit tricky to subsequently select features while making sure that no feature is selected twice, which is why the implementation is not straight forward for that part.
Let's get an overview of the lists that are used in the code:

- `features` is the list of actual features, it will not be changed during the whole process
- `feature_indexes` is the list of indexes of features that we haven't selected so far, we are removing indexes from this list as we are selecting features, so that no feature can be selected twice
- `classification_errors` holds the error for each feature that was not yet selected, it has the same length as `feature_indexes`

When selecting the best feature we take the index of the smallest error (`np.argmin(classification_errors)`). This index is not yet the feature index, but the index of the feature index. So the index of the feature with smallest error is `feature_indexes[min_error_idx]` and the best feature is then `features[best_feature_idx]`.
Last but not least we have to remove the `best_feature_idx` from the list of `feature_indexes`.

In the original code `classification_errors` has the same length as `feature_indexes` (line 70: `classification_errors = np.zeros(len(feature_indexes))`), which means that `min_error_idx` as an index of `classification_errors` can never be out of bounds of `feature_indexes`.

Hope this helps resolving your issue!

Simon

**Comment by RobinGRAPIN** [comment]
Thank you very much!

I think I did not understand how important the " feature_indexes " list was, so I programmed all with features and it's initial length. Now my programm is working really better, I am very liable to you.
